### ISSUE TITLE
Update w3up-cli readme to reflect recent improvements

### ISSUE THREAD

**Issue by the-simian** [nftstorage/w3up-cli#12]
- [ ] general updates throughout the readme to improve accuracy and alpha readiness
- [ ] update section on the "unlink / remove" command

## Notes on "unlink/remove" command
Since true deletion isn't possible to guarantee, we should have an explainer in the docs and cli that spells out what unlink / remove does, namely remove the association between an upload and your account.

At some point in the future, "real deletion" may happen in the sense that data for inactive accounts may be removed from Elastic IPFS, but that's not a capability we're planning to expose to end users at this point. At this point it's probably too soon to mention those plans in the README, etc, so the action here is just to spell out the current unlink behavior.

**Comment by the-simian** [comment]
do this after #10

**Comment by jchris** [comment]
Something like this

<img width="617" alt="Screen Shot 2022-08-22 at 4 06 39 PM" src="https://user-images.githubusercontent.com/253/186045597-bab4ccc2-3368-4266-b6aa-ea003886cab0.png">
