### ISSUE TITLE
Internal pre-alpha testing of w3up-cli by dag.house team

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/w3up-cli#42]
JChris & Yusef using current state of w3up-cli to provide early feedback.  
Feedback used to refine cli before alpha release.

**Comment by the-simian** [comment]
I feel like there's been some testing done and we've resolved several of the bugs reported. We've also triaged issues from several of the testers. As far as I can tell we've captured important issues in tickets, but if we need to leave this open we can. 
@jchris , @yusefnapora do you feel like we can close this (and open up other tickets for future rounds) or should we leave this open as the first round is still ongoing?

**Comment by jchris** [comment]
Great work everyone -- we are ready to move to Wave 1 access. This means if you have contacts who are willing to work 1:1 with you on using this (and have a reason to be excited about the new features) then you can share this link with them: https://purrfect-tracker-45c.notion.site/Welcome-to-w3up-alpha-Wave-1-4872c0196e144949a5411ddaca02cc4c

We want feedback good and bad, so don't blast this out, but do ask trusted friendly users to give it a try and let us know how it goes.
