### ISSUE TITLE
clarify "unlink" vs "delete" in README, cli help, etc.

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/w3up-cli#43]
Since true deletion isn't possible to guarantee, we should have an explainer in the docs and cli that spells out what `unlink` / `remove` does, namely remove the association between an upload and your account.

At some point in the future, "real deletion" may happen in the sense that data for inactive accounts may be removed from Elastic IPFS, but that's not a capability we're planning to expose to end users at this point. At this point it's probably too soon to mention those plans in the README, etc, so the action here is just to spell out the current `unlink` behavior.

**Comment by JeffLowe** [comment]
Moved this into the existing readme update #12 issue. 

Closing this one out.
