### ISSUE TITLE
upload returning broken files

### ISSUE THREAD

**Issue by jchris** [nftstorage/w3up-cli#55]
I uploaded a directory of json and images with w3up and with NFT Up. They had different CIDs (nothing inherently terrible about that) but the w3up one images come up broken in the browse, but the NFT Up ones are good. Check it out.

Via w3up: https://bafybeib4b42u3vrg7hnmf5iry72hg7ohfofjufhmpwwvbqeebhixvix6wa.ipfs.nftstorage.link

via NFT Up: https://bafybeibznt7zus526usebxmt3y6xe5clofe3fdg72emcipe7xmcwfgxcom.ipfs.nftstorage.link

Note the w3up image files are larger also. 

Here is the w3up session:

```
jchris@MacBook-Pro-2 w3up-cli % w3up whoami                             
✔ did:ipld:bafyreie6fnbcwqzqnlykkjonfndsbpqfgv3ukyi65pe4nh3f72wspokwhi
jchris@MacBook-Pro-2 w3up-cli % w3up upload /Users/jchris/Documents/NFTs/poppy 
✔ Succeeded uploading bagbaierafkgonqax2jr3asbxkyd7t5wms2tfpifkhjm2sppkkgqfr3ppwdca with 200: OK
roots:
 bafybeib4b42u3vrg7hnmf5iry72hg7ohfofjufhmpwwvbqeebhixvix6wa
```

**Comment by the-simian** [comment]
Here's some more detail:
- testing shows that json files are working, whereas images are not working

**Comment by jchris** [comment]
I am able to repeat with another similar directory:

w3up: https://bafybeig25bqmhceoim5rzkdrcoejjbjcolk3yxjd4ftts7fbek3xnrinzm.ipfs.nftstorage.link

nftup: https://bafybeicq7mgcarpnz4nxj5jchveczsgewyozcuhok5wydd3h7w4zxu5nyi.ipfs.nftstorage.link
